# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6FhNat14mz2hE7EYEyQW5CN0I3U-HLA
"""

#Febonacci series
var=int(input("Enter a number"))
a=0
b=1
for i in range (1,var+1):
  c=a+b
  print(a)
  a=b
  b=c
print()
print (c)
print (a)
print (b)



#palindrome number
num=int(input("Enter a number :"))
t=num
rev=0
while(num>0):
  rem=num%10
  rev=rev*10+rem
  num=num//10
print(rev)
num=t
if(rev==t):
  print(num,"is a palindrome")
else:
    print(num,"is not a palindrome")
print("")

count=0
for i in range (100,100):
  num=i
  rev=0
  while (num>0):
    rem=num%10
    rev=rev*10+rem
    num=num//10
  if (rev==i):
    count+=1
    print(i)

count=0
for no in range (100,1000):
  num=no
  rev=0
  while (num>0):
    rem=num%10
    num=num//10
    rev=rev*10+rem
  if (rev==no):
    count+=1
    print(no)

for i in range (ord(P),chr(U)):
  for

for i in range (5,0,-1):
  print(" "*(5-i),end=' ')
  for j in range (1,i+1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  print(" "*(5-i),end=' ')
  for j in range (1,i+1):
    print(j,end=' ')  #extra space will give pyramid
  print()

no=int(input("Enter a number :"))
k=no
for i in range (1,no):
  for j in range (1,i+1):
    print (j,end='')
  if j==k:
    break
  print()

a='A'
for i in range (1,6):
  print (" "*(5-i),end='')
  for j in range (1,i+1):
    print (j,end='')
  for k in range (ord('A'),ord(a)+1):
    print (chr(k),end='')
  a=chr(ord(a)+1) 
  print ()

