# -*- coding: utf-8 -*-
"""Patterns Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuW-hDfNhi1ezrA9Dl1D-RXW_ApxGSWN
"""

#1 pattern

for i in range (1,6):
  for j in range (1,i+1):
    print(j,end='')
  print()

# 2 pattern

for i in range (1,6):
  for j in range (1,i+1):
    print(j%2,end='')  # 1%2= 1 2%2=0 
  print()

a=3%2
a

a=1%2
a

b=6%2
b

for i in range (1,6):
  for j in range (1,i+1):
    print (i,end='')
  print()

for i in range (5,0,-1):
  for j in range (1,i+1):
    print(j,end='')
  print()

for i in range (1,6):
  for j in range (1,i+1):
    print(j,end='')
  print()
for i in range (4,0,-1):
  for j in range (1,i+1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  for j in range (1,i+1):
    print(j,end='')
  print()
for i in range (1,6):
  for j in range (1,i+1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  for j in range (i,0,-1):
    print (j,end='')
  print()
for i in range (1,6):
  for j in range (i,0,-1):
    print(j,end='')
  print()

for i in range (1,6):
  print(" "*(5-i),end='')
  for j in range (1,i+1):
    print(j,end=' ')
  print()

for i in range (5,0,-1):
  print(" "*(5-i),end='')
  for j in range (1,i+1):
    print(j,end=' ')
  print()

for i in range (1,6):
  for j in range (5,i-1,-1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  for j in range (5,5-i,-1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  for j in range (5,i-1,-1):
    print(j,end='')
  print()

for i in range (5,0,-1):
  for j in range (1,i+1):
    print(j,end='')
  print()

k=1
i=1
n=15
while i<n:
    j=1
    while j<=i and k<=n:
        print(k,end=' ')
        k+=1
        j+=1
    i+=1
    print("")

k = 1
for i in range(6):
    for j in range(1,i+1):
        print(k,end=" ")
        k+=1  
    print()

for i in range (1,6):
  for j in range (i,0,-1):
    print (j,end='')
  print()

for i in range (1,6):
  print(" "*(5-i),end='')
  for j in range (1,i+1):
    print(j,end=' ')
  print()
for i in range (4,0,-1):
  print(" "*(5-i),end='')
  for j in range (1,i+1):
    print(j,end=' ')
  print()

for i in range (1,6):
  for j in range (1,i+1):
    print(i,end=' ')
    i+=5
  print()

for i in range (1,6):
  for j in range (1,i+1):
    print (j,end=' ')
  for j in range (i-1,0,-1):
    print (j,end=' ')
  print ()

for i in range (1,6):
  for j in range (1,6):
    print(j,end='')
  print()

for i in range (1,6):
  for j in range (1,7-i):
    print(j,end='')
  print()

